language: java
jdk:
- oraclejdk8

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r ktapi-report/target/site/jacoco-aggregate/jacoco.xml

deploy:
  provider: releases
  api_key:
    secure: fDYuxJwE3UcKUaFa9LqWnROXiP2/4CLMK/jgFN1uOqR4jYOUYBlI2ldErd5p3R4rn9wMiixv0NxGQEn9jx4UoYf7NSZoPOd53DsFf0KQiOMP1PT2VN7de7xRknD0idf+1jl208+jQpuEvC1mVlyL/xUrOC8yGF4Tvh9KBUSbgFCqp6pmA4s7xRCBNZDcH44NVdWzvnDOqPs9+G4eIN94d7fpqzuc1+ht5nXoGIWe+R84s6EpBZ1VOZX2Y2YJmuIZGo3sP9CBYWQ+hYOdJLF3TbMKwwjLsKnnIW7QQ34BxV886CbiTCUCuRRDCzI1YP+hUSBquvOf3m/obJhvNVMEVy/8E5/x0llhUFNkQhOZVdf/dyb3C9iZjRk+Xfb4naUtm8rGVl/yt+sBoSaI5s6jDO/JCIGQGAHitCXfhynnK+JakOjZCrMh7CX7EJ1/RJ8cBQygQbJL5IJcp5RsxKs3iV1iJOzzsTq0BrdFtY+PDct4zt+4dk29QdktQNFRe3lwms4fhkqKayrHlAl3TnBfTpRYK3UlxRMfUQNLjUKPMmkFgDquVmnywFHOwIlXGEhH4IDk8oKFm6myopXPlY45aPuZa1y64E2XZeLJBRJLSO29L4JVFtZy2E99+iCQ/OXXNxy5ZQDXBKqhKrlKqh2KHnrTGx9ztcPwtBmb3IEcF4c=
  file_glob: true
  file: "**/*.jar"
  skip_cleanup: true
  on:
    repo: 125m125/ktapi-java
    tags: true

